Simplify loading default configuration
We don't necessarily need to load default values in two stages. Once
during instantiation of ConfigParser object, where we load the default
values for all sections, and later by invoking read_dict(), where we
load the default values for 'daemon' section.

We can simply load the defaults by invoking read_dict(). This also
allows us to change the type of numeric default values from string to
integer or float-pointing numbers, as passing default values during
instantiation of ConfigParser objects forces to use only strings.

I was not aware of this restriction, and I only found it when I tried to
load the configuration for a service check, which it didn't have a value
for 'check_internval' and the default value in DEFAULT_OPTIONS was
10 (integer) and not '10' (string):

    anycast-healthchecker -f ./var/etc/anycast-healthchecker.conf -F ./var/etc/anycast-healthchecker.d/foo1IPv6.bar.com.conf
    Traceback (most recent call last):
    File "/home/pparissis/.virtualenvs/python36/bin/anycast-healthchecker", line 10, in <module>
        sys.exit(main())
    File "/home/pparissis/.virtualenvs/python36/lib/python3.6/site-packages/anycast_healthchecker/main.py", line 55, in main
        args['--service-file'])
    File "/home/pparissis/.virtualenvs/python36/lib/python3.6/site-packages/anycast_healthchecker/utils.py", line 303, in load_configuration
        configuration_check(config)
    File "/home/pparissis/.virtualenvs/python36/lib/python3.6/site-packages/anycast_healthchecker/utils.py", line 356, in configuration_check
        service_configuration_check(config)
    File "/home/pparissis/.virtualenvs/python36/lib/python3.6/site-packages/anycast_healthchecker/utils.py", line 380, in service_configuration_check
        getattr(config, getter)(service, option)
    File "/opt/python3.6/lib/python3.6/configparser.py", line 824, in getfloat
        fallback=fallback, **kwargs)
    File "/opt/python3.6/lib/python3.6/configparser.py", line 809, in _get_conv
        **kwargs)
    File "/opt/python3.6/lib/python3.6/configparser.py", line 803, in _get
        return conv(self.get(section, option, **kwargs))
    File "/opt/python3.6/lib/python3.6/configparser.py", line 800, in get
        d)
    File "/opt/python3.6/lib/python3.6/configparser.py", line 394, in before_get
        self._interpolate_some(parser, option, L, value, section, defaults, 1)
    File "/opt/python3.6/lib/python3.6/configparser.py", line 411, in _interpolate_some
        p = rest.find("%")
    AttributeError: 'int' object has no attribute 'find'

The documentation of ConfigParser mentions

    [...snip...]
        __init__(defaults=None, dict_type=_default_dict, allow_no_value=False,
                delimiters=('=', ':'), comment_prefixes=('#', ';'),
                inline_comment_prefixes=None, strict=True,
                empty_lines_in_values=True, default_section='DEFAULT',
                interpolation=<unset>, converters=<unset>):
            Create the parser. When `defaults' is given, it is initialized into the
            dictionary or intrinsic defaults. The keys must be strings, the values
            must be appropriate for %()s string interpolation.
    [...snip...]