Fix a crash with python-daemon>=2.1
python-daemon>=2.1 has initgroups=True by default which requires root
privileges(CAP_SETGID capability) and causes the following since we
run as normal user:

File ".../site-packages/daemon/daemon.py", line 635, in change_process_owner
    os.initgroups(username, gid)
PermissionError: [Errno 1] Operation not permitted

Older versions of python-daemon don't have that parameter, so we set it
manually instead of passing it to the supper(), so this fix can work
with python-daemon<2.1.